---

name: Lint code base
# https://github.com/github/super-linter/
# Want to customise the linting rules for
# individual linters? See yaml files in:
#   .github/linters

on:
  push

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false  # Lint edited files only
          #VALIDATE_PYTHON: false
